baseURL = "https://morristai.github.io"
# [en, zh-cn, fr, pl, ...] determines default content language
defaultContentLanguage = "en"
theme = "DoIt"
title = "300.Watts"
# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true
